services:
  app:
    # ← اسم سرویس (همون چیزی که با docker compose up اجرا میشه)
    build:
      # ← به داکر میگه که ایمیج رو از روی Dockerfile بساز
      context: . # ← مسیر فعلی (همون پوشه پروژه) رو در نظر بگیر
      dockerfile: Dockerfile # ← از این فایل برای ساخت استفاده کن
      target: development # ← از مرحله development توی Dockerfile استفاده کن (نه final)
    user: root # ← با کاربر root اجرا کن (برای حل مشکل دسترسی)
    ports:
      - "5173:5173" # ← پورت 5173 ماشین رو به پورت 5173 کانتینر وصل کن
    volumes:
      - .:/usr/src/app # ← تمام فایل‌های پروژه رو به کانتینر متصل کن (برای دیدن تغییرات)
      - /usr/src/app/node_modules # ← node_modules رو جدا نگه دار (از روی ماشین استفاده نکن)
    environment:
      - NODE_ENV=development # ← به React بگو در حالت توسعه هستیم
      - CHOKIDAR_USEPOLLING=true # ← برای ویندوز که تغییرات رو تشخیص بده
    command: npm run dev # ← دستوری که اجرا میشه (همون npm run dev خودمون)
